const FIVE_MINUTES_IN_SECONDS = 300;
const SIXTY_MINUTES_IN_SECONDS = 3600;
const THIRTY_DAYS_IN_MILLISECONDS = 2592000000;
const TWO_HOURS_IN_MILLISECONDS = 7200000;

export {
  FIVE_MINUTES_IN_SECONDS,
  SIXTY_MINUTES_IN_SECONDS,
  THIRTY_DAYS_IN_MILLISECONDS,
  TWO_HOURS_IN_MILLISECONDS,
};
